### ISSUE TITLE
Assumes discord install is inside /usr/share/ in linux

### ISSUE THREAD

**Issue by CodeF53** [Velocity-Discord/Velocity#18]
https://github.com/Velocity-Discord/Velocity/blob/358e1d8bc4fe79777f3fd8fc1beaa80f2fe0b122/scripts/inject.js#L62

[Discord Arch Electron](https://aur.archlinux.org/packages/discord_arch_electron) installs to `/usr/lib/discord/`

This leads to a confusing error where it says it found discord at `/usr/share/discord/`, but it ends up getting a directory not found error immediately afterwards:
![](https://i.imgur.com/o6Ba7sg.png)

**Comment by TheCommieAxolotl** [comment]
Fixed in latest `v2` commit with the switch to [@velocity-discord/scaffold](https://github.com/Velocity-Discord/scaffold/)
