### ISSUE TITLE
Install filePath is returning undefined

### ISSUE THREAD

**Issue by JoshHyde9** [Velocity-Discord/Velocity#5]
> velocity@1.0.2 install
> node ./scripts/install.js --

Velocity 
Starting installation process...
Please enter the absolute path to the discord folder you would like to install Velocity. (filePath) /usr/share/discord/resources
Preparing to install to 'undefined'
Is this ok? (y/n)

**Comment by TheCommieAxolotl** [comment]
Fixed in [63fbcc8](https://github.com/Velocity-Discord/Velocity/commit/63fbcc803aac6bb59eccc90fcc3cd1aa58a03f09)
