### ISSUE TITLE
Linux Discord install directories are hard-coded

### ISSUE THREAD

**Issue by Ruthenic** [Velocity-Discord/Velocity#8]
This can lead to the application failing with an ENOENT error when the Discord install is in a different path than `/usr/share/discord{branch}`, such as on Arch Linux (and probably other distributions)

**Comment by TheCommieAxolotl** [comment]
As of [cccfef](https://github.com/Velocity-Discord/Velocity/commit/cccfeff98bfd93470466ca27831e2716e234cba1), the install script will now ask for a path on Linux unless you explicitly use the `--linux` arg. If you would like to supply alternate paths that display themselves on other distributions feel free to add another comment and I will happily add them.
